apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: cash-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: johndurkin/cash-flow:auth-v1.0.0
          imagePullPolicy: Always

          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
          readinessProbe:
            httpGet:
              path: /api/v1/auth/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: myregistrykey