FROM python:{{{generatorLanguageVersion}}} AS builder

WORKDIR /usr/src/app

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip install --upgrade pip

COPY . .
# Copy the services directory from the parent directory into the application
COPY ../services ./services
RUN pip install --no-cache-dir .


FROM python:{{{generatorLanguageVersion}}} AS test_runner
WORKDIR /tmp
COPY --from=builder /venv /venv
COPY --from=builder /usr/src/app/tests tests
COPY --from=builder /usr/src/app/services services  # Ensure services are available during testing
ENV PATH=/venv/bin:$PATH

# install test dependencies
RUN pip install pytest

# run tests
RUN pytest tests


FROM python:{{{generatorLanguageVersion}}} AS service
WORKDIR /root/app/site-packages
COPY --from=test_runner /venv /venv
COPY --from=test_runner /tmp/services services  # Ensure services are available in the final image
ENV PATH=/venv/bin:$PATH
