services:
  
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  dms:
    build: .
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    command: uvicorn main:app --host 0.0.0.0 --port ${CONTAINER_PORT}
    environment:
      - REDIS_URL=redis://redis:6379/0  # Redis connection URL
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}    
  


volumes:
  pgdata:

      