apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: {{ .Values.config.datasources.access }}
        orgId: {{ .Values.config.datasources.orgId }}
        url: {{ .Values.config.datasources.tempoUrl }}
        basicAuth: {{ .Values.config.datasources.basicAuth }}
        isDefault: {{ .Values.config.datasources.isDefault }}
        version: {{ .Values.config.datasources.version }}
        editable: {{ .Values.config.datasources.editable }}
        uid: {{ .Values.config.datasources.uid }}
        jsonData:
          httpMethod: {{ .Values.config.datasources.httpMethod }}
