apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafan
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "{{ .Values.env.GF_AUTH_ANONYMOUS_ENABLED }}"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "{{ .Values.env.GF_AUTH_ANONYMOUS_ORG_ROLE }}"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "{{ .Values.env.GF_AUTH_DISABLE_LOGIN_FORM }}"
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: "{{ .Values.env.GF_FEATURE_TOGGLES_ENABLE }}"
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-config
          mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          subPath: datasources.yaml
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-config
        configMap:
          name: grafana-config
