apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
