apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms
  namespace: cash-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dms
  template:
    metadata:
      labels:
        app: dms
    spec:
      containers:
        - name: dms
          image: johndurkin/cash-flow:dms-v1.0.0
          imagePullPolicy: Always

          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: dms-config
            - secretRef:
                name: dms-secret
          readinessProbe:
            httpGet:
              path: /internal/v1/data/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: myregistrykey

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dms-hpa
  namespace: cash-flow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dms
  minReplicas: 1  
  maxReplicas: 5  
  metrics:
    - type: Resource
      resource:
        name: cpu  
        target:
          type: Utilization
          averageUtilization: 50          