apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
  namespace: cash-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: transaction
          image: johndurkin/cash-flow:transaction-v1.0.0
          imagePullPolicy: Always
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: transaction-config
          readinessProbe:
            httpGet:
              path: /api/v1/transactions/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: myregistrykey

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-hpa
  namespace: cash-flow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction
  minReplicas: 1  
  maxReplicas: 5  
  metrics:
    - type: Resource
      resource:
        name: cpu  
        target:
          type: Utilization
          averageUtilization: 50          