apiVersion: v1
kind: Service
metadata:
  name: transaction
  namespace: cash-flow
spec:
  type: NodePort
  selector:
    app: transaction
  ports:
    - port: 8080          # The port the service will expose (accessible externally)
      targetPort: 8000  # The port the web app listens on inside of the container