apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317" # Listen on all interfaces for gRPC
    processors:
      batch:
    exporters:
      otlp/tempo:
        endpoint: tempo:4317
        tls:
          insecure: true

      otlp/traces:
        endpoint: "tlm-service:4317"
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

      otlp/sampler:
        endpoint: "sampler:4317"
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

      # Export metrics to Python service (gRPC)
      otlp/metrics:
        endpoint: "tlm-service:4319"
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s          
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo, otlp/traces, otlp/sampler]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/metrics]