apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: cash-flow
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  type: ClusterIP # ClusterIP service only accessible within the cluster
  # type: NodePort  # Expose to the outside world
  ports:
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: http
      protocol: TCP
      port: 4318
      targetPort: 4318
