apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: cash-flow
spec:
  selector:
    matchLabels:
      app: celery-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: johndurkin/cash-flow:celery-v1.0.0
          imagePullPolicy: Always
          command: ["celery", "-A", "celery_config", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: celery-config
      imagePullSecrets:
        - name: myregistrykey                

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-worker-hpa
  namespace: cash-flow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-worker
  minReplicas: 1  
  maxReplicas: 5  
  metrics:
    - type: Resource
      resource:
        name: cpu  
        target:
          type: Utilization
          averageUtilization: 50          