services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery-worker:
    build: 
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A celery_config worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0  # Redis connection URL

  service:
    build: .
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    command: uvicorn main:app --host 0.0.0.0 --port ${CONTAINER_PORT}
     