openapi: 3.1.0
info:
  title: auth #Authorization Service API
  version: 0.1.0
  description: API for managing user authentication and authorization

servers:
  - url: /api/v1/auth
    description: Authorization Service Base URL

paths:
  /register:
    $ref: ../../paths/auth/register.yaml
  /token:
    $ref: ../../paths/auth/token.yaml
  /me:
    $ref: ../../paths/auth/me.yaml
  /health:
    $ref: ../../paths/health/health.yaml
  /authorize:
    $ref: ../../paths/auth/authorize.yaml
  /validate_user:
    $ref: ../../paths/auth/validate_user.yaml


components:
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          tokenUrl: /token
          scopes: {}