apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
  namespace: cash-flow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/user-db/data"