apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
  - name: {{ .Values.service.ports.http.name }}
    protocol: {{ .Values.service.ports.http.protocol }}
    port: {{ .Values.service.ports.http.port }}
    targetPort: {{ .Values.service.ports.http.targetPort }}
  - name: {{ .Values.service.ports.grpc.name }}
    protocol: {{ .Values.service.ports.grpc.protocol }}
    port: {{ .Values.service.ports.grpc.port }}
    targetPort: {{ .Values.service.ports.grpc.targetPort }}
  type: {{ .Values.service.type }}  
