apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: {{ include "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args: ["--config=/etc/otel-collector-config.yaml"]  
        volumeMounts:
        - name: otel-collector-config-vol  
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumes:
      - name: otel-collector-config-vol 
        configMap:
          name: otel-collector-config
