apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
    - protocol: TCP
      name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}

