receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # Listen on all interfaces for gRPC
processors:
  batch:

exporters:
  # debug:
  # verbosity: detailed
  # sampling_initial: 5
  # sampling_thereafter: 200
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
service:
  telemetry:
  pipelines:
    traces:
      receivers: [otlp] # Receives telemetry data in OTLP format
      processors: [batch]
      exporters: [otlp/tempo]
      # exporters: [debug, otlp/tempo] # add backend exporters here
