apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: cash-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: johndurkin/cash-flow:notification-v1.0.0
          imagePullPolicy: Always
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /internal/v1/notification/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-hpa
  namespace: cash-flow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification
  minReplicas: 1  
  maxReplicas: 5  
  metrics:
    - type: Resource
      resource:
        name: cpu  
        target:
          type: Utilization
          averageUtilization: 50          